### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and ‘int

### ISSUE THREAD

**Issue by sk1350** [huangyh09/diceseq#6]
Hello, after running just fine for hours DICESeq failed with this error. 
[DICEseq] running diceseq for 21458 genes with 25 cores...
[DICEseq] [=========-----------] 43.8% done in 86868.4 sec.Traceback (most recent call last):
  File "/users/sk1350/.conda/envs/diceseq_env/bin/diceseq", line 8, in <module>
    sys.exit(main())
  File "/users/sk1350/.conda/envs/diceseq_env/lib/python2.7/site-packages/diceseq/diceseq.py", line 239, in main
    sort_dice_file(out_file+".dice", tran_ids)
  File "/users/sk1350/.conda/envs/diceseq_env/lib/python2.7/site-packages/diceseq/utils/run_utils.py", line 45, in sort_dice_file
    fid.writelines(delimiter.join(list(data[i+1,:])) + "\n")
**TypeError: unsupported operand type(s) for +: 'NoneType' and ‘int'**

**Comment by huangyh09** [comment]
Hi,

It looks that there are only 43.8% of the genes has been successfully finished. After that, diceseq attempted to sort the output file with the order of genes in GTF file. But due to the existence of missing genes, this sorting step fails to find all the input genes.

Do you have any ideas that around half of genes failed to comes back?

Yuanhua
