### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by KMbio43** [huangyh09/diceseq#7]
Hello, Prof Huang! I'm sorry to disturb you. I have a question to ask you. I have made some errors while installing diceseq, I think I should be installed successfully, but when running the code there is the following error. I'm not sure if it is my python environment or something else, here is my installation method:
conda create -n dicePy2 python=2.7 numpy==1.15.4 scipy==1.1.0 matplotlib==2.2.3 pysam==0.15.2
source activate dicePy2
and false content:
dice-count -a dice_count.gtf -s SRR5582776sorted.bam -o SRR5582776dice.txt --junction
Welcome to dice-count!
loading annotation file... Done.
Traceback (most recent call last):
  File "/home/MK/anaconda3/bin/dice-count", line 8, in <module>
    sys.exit(main())
  File "/home/MK/anaconda3/lib/python3.7/site-packages/diceseq/dice_count.py", line 132, in main
    _map_num = np.loadtxt(pysam.idxstats(sam_file), "str")[:,2]
  File "/home/MK/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 926, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/MK/anaconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 262, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/MK/anaconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 618, in open
    raise IOError("%s not found." % path)
OSError: I	230218	4139798	0
II	813184	16449284	0
III	316620	3758010	0
IV	1531933	19246328	0
V	576874	15693472	0
VI	270161	2536644	0
VII	1090940	18417732	0
VIII	562643	8431090	0
IX	439888	3765040	0
X	745751	10401514	0
XI	666816	8530514	0
XII	1078177	30091252	0
XIII	924431	12279986	0
XIV	784333	8578248	0
XV	1091291	15079578	0
XVI	948066	14969088	0
Mito	85779	928264	0
*	0	0	0
 not found.

**Comment by huangyh09** [comment]
Thanks for your question. It looks it still uses Python 3.7.

Before you install DICE-seq, you activated the environment (which you specified as python=2.7), right?

Yuanhua
